base_url = "https://atvari.eu"
minify_html = true
compile_sass = true
default_language = "en"
theme = "portio-zola"

[link_checker]
skip_prefixes = [
    "https://www.linkedin.com/",
]

[languages.en]
title = "atvari"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.en.translations]
contact_me = "Contact me"
start_project = "Let's start a project"
showing_all = "Showing all"
hire_me_now = "Hire me now"
get_in_touch = "Get in touch"
see_details = "See details"
sitemap = "Sitemap"
address = "Address"
phone = "Phone"
email = "Email"
categories_description = "Showing all posts with the category"
tags_description = "Showing all posts with the tag"
opening_hours = "Working hours"
form_title = "Contact form"
form_button = "Send message"
form_input_name = "Name"
form_input_email = "Email"
form_input_message = "Message"
form_input_agreement = "I agree that my submitted data is being collected and stored."
copyright = "Copyright © atvari GmbH 2026"

# Menus
home = "Home"
about = "About"
service = "Service"
work = "Work"
team = "Team"
blog = "Blog"
contact = "Contact"

# Sitemaps
about_me = "About me"
frequently_ask_question = "Frequently Asked Questions"
privacy_and_policy = "Privacy Policy"
latest_article = "Latest article"
impressum = "Impressum"

[languages.de]
title = "atvari"
generate_feeds = true
build_search_index = false

taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 9 },
    { name = "categories", feed = true, render = true, paginate_by = 9 },
]

[languages.de.translations]
contact_me = "Kontaktiere mich"
start_project = "Projekt starten"
showing_all = "Alle anzeigen"
hire_me_now = "Jetzt engagieren"
get_in_touch = "Kontakt aufnehmen"
see_details = "Details ansehen"
sitemap = "Sitemap"
address = "Adresse"
phone = "Telefon"
email = "E-Mail"
categories_description = "Zeigt alle Beiträge der Kategorie"
tags_description = "Zeigt alle Beiträge mit dem Tag"
opening_hours = "Öffnungszeiten"
form_title = "Kontaktformular"
form_button = "Nachricht senden"
form_input_name = "Name"
form_input_email = "E-Mail"
form_input_message = "Nachricht"
form_input_agreement = "Ich stimme zu, dass meine übermittelten Daten gespeichert werden."
copyright = "Copyright © atvari GmbH 2026"

# Menus
home = "Start"
about = "Über uns"
service = "Leistungen"
work = "Arbeiten"
team = "Team"
blog = "Blog"
contact = "Kontakt"

# Sitemaps
about_me = "Über mich"
frequently_ask_question = "Häufig gestellte Fragen"
privacy_and_policy = "Datenschutz"
latest_article = "Neuester Artikel"
impressum = "Impressum"

[extra]
date_format = "%d %B, %Y"
logo = "images/logo.svg"
logo_dark = "images/logo-white.svg"
footer_logo = "images/logo-white.svg"
# google_analytics = "YOUR TOKEN FOR GOOGLE ANALYTICS"
display_cta = true

menus = [
  { name = "home", url = "#home" },
  { name = "about", url = "#about" },
  { name = "service", url = "#service" },
  { name = "work", url = "#portfolio" },
  { name = "team", url = "team" },
  { name = "blog", url = "#blog" },
  { name = "contact", url = "#contact" }
]

sitemaps = [
  { name = "about_me", url = "#about" },
  { name = "frequently_ask_question", url = "#" },
  { name = "privacy_and_policy", url = "#" },
  { name = "latest_article", url = "#" },
  { name = "impressum", url = "/impressum/" }
]

socials = [
  { label = "Sifa ID", icon = "sifa", url = "https://sifa.id/c/atvari.eu" },
  { label = "LinkedIn", icon = "linkedin-original", url = "https://www.linkedin.com/company/atvari" },
  { label = "Bluesky", icon = "bluesky", url = "https://bsky.app/profile/atvari.eu" },
  { label = "Mastodon", icon = "mastodon", url = "https://fosstodon.org/@atvari" },
  { label = "GitHub", icon = "github-original", url = "https://github.com/atvari-eu" },
  { label = "Email", icon = "envelope", url = "mailto:hi@atvari.eu" },
]

[extra.address]
# phone = ""
email = "hi@atvari.eu"
address = "Salzstr. 1, 21335 Lüneburg, Germany"
# opening_hours = "Open from 10am to 6pm (close at 5pm Sundays) "

[extra.form]
active = false
# formspree_url = "YOUR FORMSPREE URL"

[extra.map]
active = false
# latitude = ""
# longitude = ""
