name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Build site
        run: nix build .

      - uses: actions/git-pages@v2
        with:
          site: https://atvari.eu/
          server: codeberg.page
          token: ${{ forge.token }}
          source: result/
