name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: codeberg-tiny
    env:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    steps:
      - uses: actions/checkout@v5

      - uses: https://github.com/DeterminateSystems/nix-installer-action@main

      - name: Build site
        run: |
          out=$(nix build . --no-link --print-out-paths)
          cp -rL "$out" result

      - uses: actions/git-pages@v2
        with:
          site: https://atvari.eu/
          server: codeberg.page
          token: ${{ forge.token }}
          source: result/
