top_title = "Kundenstimmen"
title     = "Was sagen andere über uns?"

[[testimonials]]
name    = "Daniel Heymann"
company = "CmdScale GmbH"
comment = """Ich schätze Felix's Engagement als aktiver NixOS-Maintainer und seine Fähigkeit, technisches Wissen als Mentor strukturiert an das Team weiterzugeben. Ich kann Felix als Architekten und Engineer absolut empfehlen."""
time    = "07. Mai 2026"
star    = 5

[[testimonials]]
name    = "Evgeny Satyev"
company = "upsquared GmbH"
comment = """Felix ist der Typ Engineer, der versteht, dass „schnell langsam ist" – er geht an die Entwicklung mit viel Nachdenken, sorgfältiger Planung und einem starken Fokus auf Qualität heran. Die Umgebungen, die er aufgesetzt hat, und die Lösungen, die er geliefert hat, waren immer sicher, skalierbar und leicht zu warten.

(Aus dem Englischen übersetzt.)"""
time    = "04. Jul. 2025"
star    = 5
