title       = "atvari GmbH"
description = """
# Software- & Cloud-Engineering-Beratung

Mit ❤️ für Rust 🦀, Nix ❄️ & Open Source 🌐 — wir helfen Teams dabei, sichere, skalierbare Systeme zu bauen, auf die Verlass ist.
"""
button_name = "Kontakt aufnehmen"
button_url  = "contact"
image       = "images/hero/2960351.jpg"
# video_thumb = "images/hero/popup-thumb.png"
# video_url   = "https://www.youtube.com/embed/tgbNymZ7vqY"
